### ISSUE TITLE
Performance of landing section animation

### ISSUE THREAD

**Issue by FranzSkuffka** [carrot/roots-www#30]
The animation in the landing section is really nice but It is taking quite some processing power. My Notebook is getting hot within minutes.
It might make sense to use 3d transforms or even `requestAnimationFrame`.
Pull requests welcome?

**Comment by jenius** [comment]
I'm fairly sure we are using 3d transforms. They are just large SVGs. PRs welcome if you find a way to make it more energy efficient though!

**Comment by FranzSkuffka** [comment]
Hmm not sure if it is because these are large PNGs or because rendering a disney movie in realtime on retina is kind of hardware intense.
Some animations were not 3d-ized yet. However I changing this could not convince my notebook that it is not an f-16. Don't know about energy profiling so I can not tell if this pull request is actually of any use.

**Comment by jenius** [comment]
Well, worth a shot. Thanks for taking a look!

**Comment by hhsnopek** [comment]
http://stackoverflow.com/questions/22111256/translate3d-vs-translate-performance - according to the JSperf it should
