### ISSUE TITLE
Missing jeet file in assets folder

### ISSUE THREAD

**Issue by akorn2** [carrot/roots-www#39]
$ npm install
$ roots watch
[Error: Error: /Users/Akorn/workBench/tesselations-portuguese-tiles/assets/css/master.styl:4:9 ]
- Removed @include jeet from master.styl
= compiles but no jeet files or images are loaded

$ npm install -g stylus jeet
- re-instate @import jeet inside master.style

$ stylus -u jeet -w assets/css/master.styl
>   watching /Users/Akorn/npm-global/lib/node_modules/stylus/lib/functions/index.styl
>   watching node_modules/jeet/stylus/jeet.js
> ParseError: node_modules/jeet/stylus/jeet.js:2:10
> expected "ident" or "string", got "return"

$ roots watch
[Error: Error: /Users/Akorn/workBench/tesselations-portuguese-tiles/assets/css/master.styl:4:9 ]

**Comment by jescalan** [comment]
Seems like an issue with `jeet` to me, I would perhaps file it over there!

**Comment by dbox** [comment]
They goofed and pushed a major breaking change after 6.1.2. I would recommend locking jeet to 6.1.2 @akorn2

**Comment by akorn2** [comment]
Badass, I love your tools and greatly appreciate your assistance! I'm looking forward to getting comfortable with your stack and championing your solutions.

**Comment by jescalan** [comment]
🎉 💖 -- keep an eye on [spike](https://github.com/static-dev/spike) as well if you are just getting into it

**Comment by akorn2** [comment]
Webpack! (sexy). -- thanks a bunch for the direction.

**Comment by jescalan** [comment]
@akorn2 also you're welcome to join us at https://gitter.im/static-dev/spike to chat!
