### ISSUE TITLE
Permissions Licence

### ISSUE THREAD

**Issue by akorn2** [carrot/roots-www#43]
Howdy Carrot Crew,

I'm a graphic designer learning to program. I'd love to build upon this template, but am uncertain what license you have declared upon your work.

With Respect,
Aaron

**Comment by jescalan** [comment]
Hey there Aaron!

Thanks so much for asking, and sorry we didn't have one already! It's licensed under MIT, I just added the info for this to the repo. Thanks for catching and calling us out, and looking forward to seeing what you build!
