### ISSUE TITLE
Mobile Navigation

### ISSUE THREAD

**Issue by hhsnopek** [carrot/roots-www#7]
When navigating on any device that is smaller than 605px, the nav bar disappears. I would like to create a hamburger menu for the smaller devices.

Update: The reason I'd like to add this is because it's hard to navigate the site without the nav bar

**Comment by hhsnopek** [comment]
I'm playing around with this, but so far I can't find a way that keeps it looking nice. Any ideas @jenius ?

**Comment by kylemac** [comment]
why not just an inline-list of the links? even if they dropped to the blueish area, it's be usable.

**Comment by hhsnopek** [comment]
That works, but once we hit 350px in device width the list + logo seem too compact (I can keep adjusting the styling to work if we're fine with it being that tight)
![inline-list below 350px](https://cldup.com/hFkA3Pj4OZ.png)

**Comment by kylemac** [comment]
I'm thinking an inline-list, where they are stacked all horizontally (not
vertically)

**Comment by hhsnopek** [comment]
They're all stacked horizontally until ~600px which then it needs to stack vertically or drop below the logo to stay horizontal, but it'll have to stack vertically at some point. Unless you were thinking about a horizontal scrolling like on carrot.is

**Comment by hhsnopek** [comment]
Keeping it vertical once it hit's 600px I can get it down to 320px and it'll look like this:
![](https://cldup.com/t3JadBe3Pg.png)

**Comment by hhsnopek** [comment]
@kylemac I've pushed the styling for this layout to keep in the history if we'd like to revert to it. Otherwise I'm looking into the horizontal styling now :smile:

**Comment by jenius** [comment]
That definitely does not look good

**Comment by hhsnopek** [comment]
Yeah it's pretty cluttered - I'm not a fan of it either, but holding it there for the time being

**Comment by hhsnopek** [comment]
@jenius what about any of these? http://tympanus.net/Development/PerspectivePageViewNavigation/
I'm now putting the links below the logo like so: Note I'm going to have to change up the overflow on the `nav` element for this way to work
![](https://cldup.com/FWNzZTCvQA.png)

**Comment by jenius** [comment]
That's fine, but let's get them padded down a little bit below the cloud line?

**Comment by hhsnopek** [comment]
yupp! I gotta fix the overflow of the nav (container of logo and links)

**Comment by hhsnopek** [comment]
So we get down to around 360px and it reaches across the whole screen, once we get down to 320px it gets pretty squished, do we want it to drop down to two lines?

Squished:
![](https://cldup.com/Nf256vJpz3.png)

Dropped down:
![](https://cldup.com/VsYD67gjXe.png)

**Comment by jenius** [comment]
Can we just get them in a vertical list with a slightly darker purple as the background? Something like this?

![nav](https://cloud.githubusercontent.com/assets/556932/6196054/83ee2f90-b3a2-11e4-8b9b-4812b55407df.jpg)

**Comment by hhsnopek** [comment]
A or B - the difference is the header spacing

A:
![option a](https://cldup.com/lBmnflks1M.png)

B:
![option b](https://cldup.com/Bg5wMS_Js2.png)

**Comment by jenius** [comment]
A, with a little more spacing on the top

**Comment by hhsnopek** [comment]
A with more spacing:

![Option A more spacing](https://cldup.com/iVcJ3e42NL.png)

**Comment by jenius** [comment]
Yup. Now just make sure the spacing on top and bottom are even, lighten up those divider lines a bit, and round the corners and we're set

**Comment by hhsnopek** [comment]
Alright spacing between logo, nav, header are equal, divs lightened up, and corners rounded:

![final?](https://cldup.com/Vn_8xvqJ5f.png)

**Comment by jenius** [comment]
Perfecto

**Comment by hhsnopek** [comment]
gonna rebase quick, don't merge yet! :smile:
